version: 2
jobs:
    build:
      docker:
        - image: circleci/golang:1.12
      steps:
        - checkout
        - run:
            name: Run tests
            command: |
              go test ./... -v -cover -coverprofile=coverage.txt -covermode=atomic
              bash <(curl -s https://codecov.io/bash)