version: 2
jobs:
    build:
      docker:
        - image: circleci/golang:1.12
      steps:
        - checkout
        - run:
            name: "Create a temp directory for artifacts"
            command: |
              mkdir -p /tmp/artifacts
        - run:
            name: Run tests
            command: |
              go test ./... -v -cover -coverprofile=c.out
              go tool cover -html=c.out -o coverage.html
              mv coverage.html /tmp/artifacts
        - store_artifacts:
            path: /tmp/artifacts